// Generated by CoffeeScript 1.7.1
(function() {
  var timedWhile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      if (_.all(this.scores(), (function(score) {
        return score > 21;
      }))) {
        return this.trigger('bust');
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('stand');
    };

    Hand.prototype.play = function() {
      this.at(0).flip();
      return setTimeout(timedWhile(((function(_this) {
        return function() {
          return _.any(_this.scores(), (function(score) {
            return score <= 17;
          }));
        };
      })(this)), ((function(_this) {
        return function() {
          return _this.hit();
        };
      })(this)), 750, ((function(_this) {
        return function() {
          return _this.trigger('dealerScore', Math.max.apply(null, _this.scores()));
        };
      })(this))), 750);
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    return Hand;

  })(Backbone.Collection);

  timedWhile = function(condition, callback, time, final) {
    if (condition()) {
      callback();
      return setTimeout((function() {
        return timedWhile(condition, callback, time, final);
      }), time);
    } else {
      return final();
    }
  };

}).call(this);
